# Generated by Django 5.1.4 on 2024-12-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='panner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
